name: Submodule Sync
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch: ~

jobs:
  submodule-sync:
    name: Submodule Sync
    runs-on: ubuntu-latest
    steps:
      - name: Submodule Sync
        uses: mheap/submodule-sync-action@v1
        with:
          path: LearnBlok
          ref: version-3
          pr_branch: automated-submodule-update
          target_branch: main
